// <auto-generated />
using System;
using FacturasIA.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacturasIA.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729162557_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FacturasIA.Platform.Iam.Domain.Model.Aggregates.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RucNegocio")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Aggregates.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Aggregates.Factura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoProcesamiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResumenIa")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("facturas", (string)null);
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Aggregates.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Entities.ItemFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("FacturaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("item_facturas", (string)null);
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Aggregates.Factura", b =>
                {
                    b.OwnsOne("FacturasIA.Platform.Invoicing.Domain.Model.ValueObjects.Monto", "Monto", b1 =>
                        {
                            b1.Property<Guid>("FacturaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Moneda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("moneda");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("monto_total");

                            b1.HasKey("FacturaId");

                            b1.ToTable("facturas");

                            b1.WithOwner()
                                .HasForeignKey("FacturaId");
                        });

                    b.OwnsOne("FacturasIA.Platform.Invoicing.Domain.Model.ValueObjects.NumeroFactura", "NumeroFactura", b1 =>
                        {
                            b1.Property<Guid>("FacturaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("numero");

                            b1.Property<string>("Serie")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("serie");

                            b1.HasKey("FacturaId");

                            b1.ToTable("facturas");

                            b1.WithOwner()
                                .HasForeignKey("FacturaId");
                        });

                    b.Navigation("Monto")
                        .IsRequired();

                    b.Navigation("NumeroFactura")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Aggregates.Proveedor", b =>
                {
                    b.OwnsOne("FacturasIA.Platform.Invoicing.Domain.Model.ValueObjects.Ruc", "Ruc", b1 =>
                        {
                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("ruc");

                            b1.HasKey("ProveedorId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("proveedores");

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");
                        });

                    b.Navigation("Ruc")
                        .IsRequired();
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Entities.ItemFactura", b =>
                {
                    b.HasOne("FacturasIA.Platform.Invoicing.Domain.Model.Aggregates.Factura", null)
                        .WithMany("Items")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacturasIA.Platform.Invoicing.Domain.Model.Aggregates.Factura", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
